[package]
name = "autograder"
version = "0.1.0"
authors = ["Alex Thomas <alexthomas@berkeley.edu>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
rand = "0.3"
rayon = "1.0.3"
crossbeam-utils = "0.6.5"

